{% set name = "dtool_ecs" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool_ecs/dtool-ecs-{{ version }}.tar.gz
  sha256: bae76be9b443f5580877215a6a2b8d97c18cce995b037c5023bc2bf32574b2d1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - boto3
    - click
    - dtool_cli
    - dtool_s3 >=0.7.0
    - dtoolcore >=3.10
    - python >={{ python_min }}

test:
  imports:
    - dtool_ecs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jic-dtool/dtool-ecs
  summary: Add ECS S3 support to dtool
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
